<#
.SYNOPSIS
    Turns tools/icon/icons.txt into src/BertBrowser.App/Resources/Icons.xaml.

.DESCRIPTION
    Fetches each icon named in the manifest from Fluent UI System Icons (MIT) and writes its outline
    out as a WPF Geometry resource keyed by the job it does, so a call site says Icon.Back rather
    than a codepoint nobody can read. See icons.txt for why the app stopped using the Segoe font.

    Nothing here is clever on purpose: an SVG this cannot convert exactly is an error, never a
    silently dropped subpath. A missing piece of an icon looks like a design choice, which is the
    same class of bug -- a wrong picture that compiles -- that the manifest exists to stop.

    Run it when icons.txt changes. It needs network access; the app never does.

.EXAMPLE
    pwsh tools/icon/build-icons.ps1
    pwsh tools/icon/build-icons.ps1 -WhatIf     # report what would change, write nothing
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [string] $Manifest = (Join-Path $PSScriptRoot 'icons.txt'),
    [string] $OutFile  = (Join-Path $PSScriptRoot '..\..\src\BertBrowser.App\Resources\Icons.xaml'),
    [string] $Ref      = 'main'
)

$ErrorActionPreference = 'Stop'
$base = "https://raw.githubusercontent.com/microsoft/fluentui-system-icons/$Ref/assets"

$entries = Get-Content -LiteralPath $Manifest |
    Where-Object { $_.Trim() -and -not $_.TrimStart().StartsWith('#') } |
    ForEach-Object {
        $f = $_ -split '\|' | ForEach-Object { $_.Trim() }
        if ($f.Count -ne 4) { throw "icons.txt: expected 'Name | Folder | file | size', got '$_'" }
        [pscustomobject]@{ Name = $f[0]; Folder = $f[1]; File = $f[2]; Size = $f[3] }
    }

$dupes = $entries | Group-Object Name | Where-Object Count -gt 1
if ($dupes) { throw "icons.txt: duplicate name(s): $($dupes.Name -join ', ')" }

Write-Host "Fetching $($entries.Count) icons from fluentui-system-icons@$Ref"

$geometries = foreach ($e in $entries) {
    $url = "$base/$([uri]::EscapeDataString($e.Folder))/SVG/ic_fluent_$($e.File)_$($e.Size)_regular.svg"
    try { $svg = (Invoke-WebRequest -Uri $url -UseBasicParsing).Content }
    catch { throw "$($e.Name): cannot fetch $url -- $($_.Exception.Message)" }

    # Anything that is not a <path d="..."> carries outline this script would drop on the floor.
    $shapes = [regex]::Matches($svg, '<(circle|rect|ellipse|polygon|polyline|line)\b')
    if ($shapes.Count) {
        throw "$($e.Name): $($e.File) uses <$($shapes[0].Groups[1].Value)>, which this script cannot convert. Pick a different asset or extend the script."
    }

    $paths = [regex]::Matches($svg, '<path\b[^>]*?\bd="([^"]+)"[^>]*>')
    if (-not $paths.Count) { throw "$($e.Name): no <path> in $url" }

    # SVG fills nonzero unless told otherwise; WPF's path mini-language defaults to even-odd, so the
    # rule is always stated. Mixing the two inside one icon cannot be expressed in a single Geometry.
    $rules = $paths | ForEach-Object { if ($_.Value -match 'fill-rule="evenodd"') { 'F0' } else { 'F1' } } | Select-Object -Unique
    if ($rules.Count -gt 1) { throw "$($e.Name): mixes fill-rule nonzero and evenodd across subpaths; needs a GeometryGroup." }

    $d = ($paths | ForEach-Object { $_.Groups[1].Value.Trim() }) -join ' '
    $d = [regex]::Replace($d, '\s+', ' ')

    [pscustomobject]@{ Name = $e.Name; Data = "$rules $d"; Source = "$($e.Folder)/$($e.File)_$($e.Size)" }
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('<!--')
[void]$sb.AppendLine('    GENERATED by tools/icon/build-icons.ps1 from tools/icon/icons.txt. Do not edit by hand:')
[void]$sb.AppendLine('    change the manifest and re-run the script, so the name -> picture mapping stays reviewable')
[void]$sb.AppendLine('    in one place. Artwork is Fluent UI System Icons, MIT licensed:')
[void]$sb.AppendLine('    https://github.com/microsoft/fluentui-system-icons')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    Draw one with the IconPath style, never a raw Path:')
[void]$sb.AppendLine('        <Path Style="{StaticResource IconPath}" Data="{StaticResource Icon.Back}"/>')
[void]$sb.AppendLine('-->')
[void]$sb.AppendLine('<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"')
[void]$sb.AppendLine('                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">')
[void]$sb.AppendLine()
foreach ($g in $geometries) {
    [void]$sb.AppendLine("    <!-- $($g.Source) -->")
    [void]$sb.AppendLine("    <Geometry x:Key=""Icon.$($g.Name)"">$($g.Data)</Geometry>")
}
[void]$sb.AppendLine()
[void]$sb.AppendLine('</ResourceDictionary>')

$resolved = [System.IO.Path]::GetFullPath($OutFile)
if ($PSCmdlet.ShouldProcess($resolved, 'write')) {
    [System.IO.File]::WriteAllText($resolved, $sb.ToString(), (New-Object System.Text.UTF8Encoding $false))
    Write-Host "Wrote $($geometries.Count) geometries to $resolved"
} else {
    Write-Host "Would write $($geometries.Count) geometries to $resolved"
}
