namespace BertBrowser.Core.Services.Metadata;

/// <summary>
/// The containers nothing here can write: each encoded by Windows' own media pipeline, so the tag
/// codec is always reading and editing somebody else's file.
/// </summary>
internal static partial class MetadataFixtures
{
    /// <summary>
    /// A quarter second of 8 kHz mono tone as FLAC, with no tags.
    /// <code>MediaTranscoder, MediaEncodingProfile.CreateFlac(AudioEncodingQuality.Low), from a hand-built 16-bit PCM WAV</code>
    /// </summary>
    public const string Flac =
        "ZkxhQwAAACIQABAAAAJ3AAN3CsRC8AAAKwzEgXifQRwohRypVi6DHZEDAwAAEgAAAAAAAAAAAAAAAAAAAAAQAIQAACggAAAAcmVm" +
        "ZXJlbmNlIGxpYkZMQUMgMS41LjAgMjAyNTAyMTEAAAAA//jJiAAjFAAAAAQACT25TTbLlpfS99KWlpS6X0vS/TTZdPy/5SlPynyl" +
        "MppKfPzynlPKfLPylNP//9Ol6aUu/0u+l6Wl9L6X0vSlLL//8spSnylPKfPynKcp8plPzTKdC+U9P//6UuVOypv0ul6Xvpfff9/S" +
        "lL///llPylNJZlnQs+fPlOUplPylPlOn05fT003+l+/S0vsqb0ul9L6X9NL///lKU6ZZ8s+UylMp5TymWfnlKU+Up///T0pcidL6" +
        "WlL6Wl7Km+l6XTf6Usv//5SlNPKfmhc0ynKeU80LKcp8pT8pT///ppZfSl++l6XS9Lpel9L7L02Xl6eXl8pTLlnlPlOU+U5TmmWe" +
        "U/KU5SlKfL/6dKbLTZaUtKX3pfe/sqUvSl00pS/0/LyylPlNCyn58plNCymUymnlPKf5TTpy//TSl9NyJpdL6XvpaXpvv0pelLLL" +
        "+n8pZSn8ppKUylMs8pynz5TylJSmnKU9OmX+nT39KXS/vvpdL2XS9L0pfpZZf0+Xy5p5Snynz5T55TlPlOUp5T/KU//5E6aU30pf" +
        "v2RNLS9LTS79lpsvTS8v9Py5SlMuU+aZTQs+Uyn5SUpllJZT0LKdP//9KXL0vTZbKmypSJZU0qX7LTZdNLLy//5cpTlmnKeWfPKf" +
        "PKUlPlNJZ/ylP//9OlL9L9lpfvS9LpaaXpaUpfSlLl08v/lP5SnymUpyn55pLPKZSlPKeXKU///6Upf7LSypsib0vfpaX0v7/Sy/" +
        "//y5p/KfKaFKZSnnz8/PlPlKZZZTp///Sl/pfpdL77Km++y030v6UvL//LyynylPlNJT5+fPz5+U/NPlKdP//6aX+l9L6Wl+9LpS" +
        "76UvsielKX///KU0+U6FlMp+aSnlKFnKfzSWU/KU/+mX00psvZelLSlpul6Xv0tN9NL0pcv//8pSnylPlOU/PlPPKfKcp5Zpyymn" +
        "//+lLLkTS6b0pdLpfel030vSl06Uv0l/8ssp8pp5oWacplNJT5+U5p5ZpLKU///6aWX9LTfpel0vS0sib9l030pS5afl/yyn8p5Z" +
        "5T5TlPOhSmU+U/NOWWaf//0ppfpS9L0paXpe+l99l9lT0pf//5ZSmnLP5TKUllPPKeaZSkspyz+Up6f/9OlLL6XpS6X2VL0um+9L" +
        "9KX0pZfp/l5ZT/KfKeU8AAAAmQj/+MmIASQU/z//PQAPKZTSWeflPlPyylP/l09NLL0pfpU3976XpdL0v7L0pS5fT/y5TTLlPKfl" +
        "OU5TlNMplPylJZ/KUpp/y+mlKUvpfpel6XS9Lpel9l0pfsuXLp/Lyyn+U5SnlMpT55plKSnyn5TTKU0pply6fppdOlLpS0pE3Im9" +
        "lTelppfS/pS8vp/yyymnKfynKfNOfKZSmWeU+UplylNP/l9NNL9L/fS6Xv7IlKm+l+l+lLL5dP/KUppln8plKcp8+aSzlPLPzTlm" +
        "mnT//p0v9L9/ffS6Xpfel/S/pZf//y5ZplKdJZ5pynz5Tnynyn5T5SmlP//+ll6b9L0vpU3pel0vpfS/ppf//8spT5SnynynPynn" +
        "zQs0llMs6ZZSn6f//Sy6aXpfSlSlTfffSl0tNl/ZeX//8pp8pTyz55T5TKUlKcp8pyz/ln//9OlKX9LpS00tLIm+9L0vSl0v+ll/" +
        "//ylKflPlPlOUplPNMp5TlKeUp5ZSn///TS/pS+l79Lpe/S6XuROl/pf8v/8pTplmksp5TlPKefKfPlNC5/KU0///6Uv9L6X0ul9" +
        "99LpZE79/pSl/8tPlmn+U/NCzSWeUylOU+eU/lPyzT//+nTf0pfelL0tL0vS0379KXppf//5cs/5T5plnymU5SnnlPKUyyn5SnT8" +
        "qf/S5fS/v0tN0vS9kTS6WVNL6aX///LKUp805Z+U88p5TlPlOU+WU5SlP/Ty9OlL+y9N6XS/el0pE36Xpf9ly//5cspplmksp80L" +
        "PKfPKfNJSnlKcspSn+X9Omm/Sy02RN9LSyJpaXpel9NlTZS5dP/yylP80ylPPynnz5T85SnlnllNNP5f6dKX9L0sul0vS9+y2VKX" +
        "0uXpfLyp05ZZSmhZTTlPz58pynKU5Tln5/ynTp8v06dL6UvpfS6X32VL6XSl0pfSlKXLT6S5ZZp+U8p/NCnlKcpLPKfmks6cs06f" +
        "y/p02XTS+l9LS+l6Wy030uml9KUpf/05ZSmnylOU/KZTylMpynynmmWdMsp09Pl/0pS9NL6XpdL996X2ROypv00suX//llKflPzT" +
        "KaFn55TKU80lKeUp5ZSnSX9P/Zf6WmlkS9LIm6WRN7Lpfpf2Usv//+aeXKcs/KSlOU8/NJZ5T8p+Waf//6aUpel+lkTfS99++l9L" +
        "7+AAAACM6P/4eYgCCwsgFABhAFsADS8v//5Sn5T+U5T5Tmks+fKfPyz8ppp///pS5ab+/cqbS9KVL0pdL9lpppZdPl/5SmmWU/nm" +
        "nKUlPKcpSWUyn8p+Upp///ppS6Uv6XS+lTffvSlTf0vSlKX//+XNPlKeU0llMpynz5/KSz5Snyymn//+lKX9LTS+lSl96XpdL0pd" +
        "LyJ0sv//+WaeWU5Z/PKcp8+aSn5pylPynT0+XT06Uv0paUum9LSypS79LSl03/Sl///llNP5pynynmmU8pLKefmnKf5Z///T6Uv6" +
        "XpS++l0vfpaX99LLTSll///lKdOU/KU5TlPKcp5T5oWUyyn8pT///TSll00vvpfvS9LpdKVNlpS/Sy5f//5p/lPLPz5pKfNJSkpp" +
        "ynylPKU9P/+nTSyp0vpZUvS9KRL0pdkTS/S+mlyJ/+Xyyn8pTzTlPKcpTKeaZSks0LKacpTTT5f+nSy6aX0siUqUvvvpdL6XTS+l" +
        "LKX+n+WUp/KflPKeU8p55T8+acpT5SnT05ctNNNL6Uv32VN9LpdL7+/S5UpeWX6fLlylJeU8p8p5TLPKZSnKUlnyn+Uppp5f9NNK" +
        "XTZe/ZdL30tKWm9L6Uv0pcv+n5ZZT+U0KU+UpKedCz5SWflPlPylOn0l+VOlllpv6WlL776XZU399KXSlLLl/p/KUpTLOmWfP588" +
        "p5TynzSUp05Sn0/l009NL00ul+l0vS9LS+l6XpS/TZZen/L5SnyzTlPKfKZTynzyn5TlnyylNP//6Upf0vpel6Xpe+/SlSlpSy00" +
        "pf/Lp5cpTyzT5QsppKZSnyUpTyU2UoULIlOZtSkMNRBAAAAAFcg=";

    /// <summary>
    /// The same tone as AAC in an MPEG-4 container, with no tags.
    /// <code>MediaTranscoder, MediaEncodingProfile.CreateM4a(AudioEncodingQuality.Low)</code>
    /// </summary>
    public const string M4a =
        "AAAAGGZ0eXBtcDQyAAAAAG1wNDFpc29tAAAAKHV1aWRcpwj7Mo5CBahhZQ7KCpWWAAAADDEwLjAuMjYyMDAuMAAADFhtZGF0AAAA" +
        "AAAAABAhelP1rhjRQIOiy93YSLCUSoqUUKV+wkQmybdJ3fHxDP0gDjXskiIJEIP4vzOYYaggVPW1bVPRZil5Ox2OKiSFyD9tsqSU" +
        "Z5lu5tUaL5rJpIuvOga1mo1KcDbpUqkmIq/YVFGRew2tGNUUCJ0si7yqe6t6zGvFG0TDqt4aQd2BJpsczWvI3rrRU44hJ2yyz3Ak" +
        "m6p7dtLvaMFpRpAMHUGKem9AU4tOW+yu8hqk3oiIquTa8XmbTyvevhBbbAK++69Re55yGnypfq3nW5kW5JjiMaEv64c7Ck5bi3LZ" +
        "TRU5TNLQ0mIFN7bJlSqqU7Fts5bVoZJXipLhpgWE7Qvnc8rSpF6pUTZliNNAWzTUXyLIAEUcKU87nofUOiEaUgWQBMyCtJ//zHk0" +
        "SVUgrQIpMkoAAyLXOWIu9gEswbH4EQlYNqVJpYe3q1y9esZ8d9Bnjnj293eC7uDvXPvn0DRZ0b9RAIVW/VAdKuHzS5We1l03rqoT" +
        "tkoXmw9+/UuL5SrmM8TXvXwp3H4Klg2dtcenrz2nRPORyPxspVbrtSvPN3Eq5V9QUVX01M/NpYC7m/nDpGGyJ77yeSTOvTdZy+11" +
        "XXliLxo92zXuIcK7x8KVmeulcUwxilx51XBM1dC5693Vr1K9PBBBbqlimgZ1yv1hLC7hknlq62tg9l2fcxVQlR2SzS8bNFz7BOrK" +
        "MriRqrOjVi7X1WDwbUfO3xrB3LKlch6ppg3sygS6HoRaVAAA9D6h1CEaU+2QBxBjQFlh+BUQm5dSxSASigWEk8dwRHGeWCXWw2fH" +
        "TE1lKJNrn7mmkWYzxM5tmSqzt5IqlsdtBd1LSESvakt0EyxBGRaMDFeJdFjsNzSxB3pek33jupN1Gsbwtx5tSUxPb01XvNKv1kEw" +
        "uwwAHkvXC/+e2yvKh8t709u2qkNxEAnNnZA5LUCTxZjDNdOiDVPiRtpMKqkDkiYzcqjlrvpFF3DLNWuPgt3fvrkkvL32LnJYPLus" +
        "ZerXPtuJ5y1FnnOWf3s0FbVfN3PspPfwr2osDniCUIc6xNUCT0ScYhZMbaZOzDGyTv1+B3TS30nPFJKKXIMgYMGE1wNOPFPVKX15" +
        "5gk/7fBWq12d8OVU5z7wi6RQAAPQ+ochGlPFkAURaQhwiU3xKUuEpAVBQBnfM75Yj0r2AS+Ipie2DIQTGLLM1JbQNSimlRKkFEev" +
        "Fomn0uOekNbZMeiXVxH6c+hWZa6iS2Auj8c6zjQMPkYAuukjgrqFrWVEVuzLf0dmmunJJhq77BVTGPsTgCNMle/OuLUkkvutr765" +
        "6EzKx0ziRCJslqU5aLLaMU8t2WzRM2WqYJFugy8Zce3v6hO4+z1clBZ7Sk39tKRrBudPy0+7WmON/bj34ZTVEGRUjXfqkP8b91dE" +
        "+Ul84YP679kU0d1u2nb66zJ6gvutClYkoNIvid+59zTz023GVfok3zrm3X39nYOdVsCI7bAGPxcverlXLPInP3/zBx4TBSrHYyzQ" +
        "sX+DAAAeh9Q4IRpTnZAHEGkBFZxVSWKSCoKvCUICmis/wiPq3mVZfjSl/ru9ojZImBW1ZgXlgTQU+U6ii3gvRLXOOUejZBCzdRY/" +
        "jXXWzAC5TMkm0zMjZlXkK3QT8Mli6an1W/qipQt5KOVJdILlYdtn6plY96aBHglC8azz7IyzzOjyfjuq1x+LcbtUnmwUFO455Zp/" +
        "VuIa7teK10CJBTUA1BmgyNg9yJItSBpskvGRaqqY0hvf6kvGwd+7zbCxXyVxZ0piO+eqwN1q86mF7Jx2OzsPryk4ZDTqiyvTSx/U" +
        "8KvtZdduLG7MNQJ5EoDUR0gp7Ztkx0Zn1+XRUc6zt3+E+FpO2RjJBM0WHdiS2buyTveifUUmdFa38rDIjVwAAPQ+ocIhGlO9kAcS" +
        "aAdExFWQWCCoFYBU1KSlkSHcPUxP5aFwLeRvfRhKz3mS4r2WdoVJdMO8UqgbKfjLnPioaQqosGAzEpHYjwPyRIW2GqJx54Jd63nR" +
        "bquIvsQXqxld6FvZvGDTOJtzPHPYw26cJT0m/VT7w6g8u2d+TlTP6cmJb53fN/f3/x3bLEDvn3S1k1ykFejDM25a8OFDz6Qum14z" +
        "Yssm8440aspp0NqRwPzXYkW/pnTXo19tFEtwxZfLJd7rqqN8snPhc+ckTlJQ99UFMMtNeFNFfLX0pu19pXPrmm6dVPpmitymXYVM" +
        "uFmjpNnMOFlud3q3c+6/MpNmX5fsLA/2mWm/sla/v07c9MvlCv2K0WEAhw2OEW2z2yOo2rUAAB6H1DwhGlP1kAURaRT2aajJS6q4" +
        "lXkgCoAaEIrqsQwXd7P59RUI+ckLiVBYvlCnkhky4idpTSZScJEi2dAnTROukWa2pZeG44n44GBwNWMafXGpyWjv1bGRxkCbv4uq" +
        "udFEKD3/CmimT2KKO0XSYnW0ndBgcuF9JXeNqowbb+echSS415oi0KCEyzR3MOcVoWGjluibNk1XXB0n7a0vfu0axuwiOvTDUTon" +
        "71+bBwplq8Hu8NFXVLJA39MV9nb4YS+namhpNytLmtwznGxfUCJJ9g76H2YJP0+cFxCfKIKeMwr1ezZ3kovJW/QpFS7f6c6CqwLh" +
        "Vs5vx3vqWOubn21eu7hLQmqy+2w9V8tQcuuzTvXK3KqseXbzAzovAAA9D6hzIRpTxZAHEGTBWIDokM0yJVqtVXFSgoGpPNK64cQy" +
        "XzkJ9riEpSmMZoF04z6qeGWwklaIJ1OgD7l9RcS3mlyZOFkgjG422iCC3E0JbQE7ecw6B+nHkoVT+xxI8gdyaqp4/IoR0L7J/JaN" +
        "vOa91Ki7NwsNnKcs6WI4ukXRZR1XUbZ4SzVV1bs5eRy988/CTvOjfhfbrvIs5L4Z+wTrF3OoBTKi9orbPApa76rpc/nlqeG+el40" +
        "+Rcp2UKDEkmaS2lAtmLHyySm0gMwF1wt8iEYK8suxy6BBbBaGAbKIoyDOFlJZabyULx7GEwk2A6JR4aAbyIxwCvx0bMKlG2oUfDn" +
        "3Lfqlr7LJbZzbizYHqH7rwEMzl7SrCiDSSuSMgjNAAAPQ+odIRpTxZAFCmfAWLAWGEasqCzJWoBGXWay8BSD9iuuIEsD87SPOopC" +
        "CqcjBIU23FhoNWKOWdVkhTeqMEwSV9jRoO0RU2wrMXm3B66Iky++p8+Mu31hevfPo2bp+5v58i7vmVm2vNPr9Li4MfbYVkjbNuNg" +
        "VdWGU2jOTsa9t0pXS8wm3zcXfjSiYWyJbyOWuMdenaMnEJOB75Lsd3vspabTjZ0WfUsx1HT5czszsm7XW+wdNB/x34m9hXQewzZC" +
        "SaXL5N7beKnXtafnTz1i82NxViLIt9k05vr0/1wnH5DjUkdmOQuc9oynjOGd/KxRF3WQ4MaDoAEbE0hGetcnVyi0UhUpVvJ7u9GU" +
        "bsOq7PFrurDLdVTZxvevH4ERScRluqlWoAAD0PqHIRpT3ZKTCWkgXgPjy3oM0VFSRCpkiqtjWQIEaUnZmDgtq0JJKh0WpeD2IuA0" +
        "7BYPerJ2X8uzYw4toSzfnQt3GvEaMgc6xRUKZKUJJuBnM41TPUEsGOhJnzBTBIZNrACQaUw9h0HHkllCmUFz6h154K7HQK3Wj6a+" +
        "+yWuM77fXK1yq/xSVJttUXXylEzW5YvFGm/Yi2xLTvnKXCuCu++BXz5sW2oe/5SYHlaM/NcqFxuWlepOgZGAX58+rjnflHtePL0f" +
        "jetyzw8sMBWUxRKG+WzvuxUckELbOqVJq242ki50XLpHKTsahZKDc7eMtyYTWugQNJyXynUkS92JhQDEYA0L06uzG5K8kSoGiTMR" +
        "mpnCk5o6SMdhkU1j86uO56H1NZAgRpSdIRpUBbqWwyYIQPbXwHHcQTNbsoAGNZSIweAgAoDEXxED8evJFkkp8YmERGHMIzY0soJA" +
        "Hyf9xvQkU/c5FKv3BO6WgRd/eLcN4jorVWG3jlKqrB0DP0bdu3h51VecvmKV4lhWqjlLCOgcbRY6Bfa9d5Gq5KrSKyzK51JilbWC" +
        "sSeNosdfvr1DV2Fkl0jKkpcjKsy+yqLEnxLCxJ/19Qk2K8YoE4KHXGJDxh6ZiFkrGmZxYsFaHEK5KZkGnnybsufLnyNZGs3NmVBz" +
        "c827mgf3FnyZx75Fs0Zj8/NmObLAWeZ0mvjOB8HzBuFPNBzNoz5XSzhoe40DQ3C2eDRnmM+ke75h7n8QHofU1lIjB4CACgMRfeIA" +
        "AAKibW9vdgAAAGxtdmhkAAAAAObp7brm6e26AACsRAAALAAAAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAA" +
        "AAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAel0cmFrAAAAXHRraGQAAAAB5untuubp7boAAAACAAAA" +
        "AAAALAAAAAAAAAAAAAAAAAABAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAGFbWRpYQAA" +
        "ACBtZGhkAAAAAObp7brm6e26AACsRAAALABVxAAAAAAALWhkbHIAAAAAAAAAAHNvdW4AAAAAAAAAAAAAAABTb3VuZEhhbmRsZXIA" +
        "AAABMG1pbmYAAAAQc21oZAAAAAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAAA9HN0YmwAAABkc3Rz" +
        "ZAAAAAAAAAABAAAAVG1wNGEAAAAAAAAAAQAAAAAAAAAAAAIAEAAAAACsRAAAAAAAMGVzZHMAAAAAA4CAgB8AAAAEgICAFEAVABgA" +
        "AAF3AAABdwAFgICAAhIQBgECAAAAGHN0dHMAAAAAAAAAAQAAAAsAAAQAAAAAHHN0c2MAAAAAAAAAAQAAAAEAAAALAAAAAQAAAEBz" +
        "dHN6AAAAAAAAAAAAAAALAAABGQAAARcAAAEbAAABHgAAARwAAAEjAAABHgAAASMAAAEmAAABJgAAARMAAAAUc3RjbwAAAAAAAAAB" +
        "AAAAUAAAAEV1ZHRhAAAANW1ldGEAAAAAAAAAIWhkbHIAAAAAAAAAAG1kaXIAAAAAAAAAAAAAAAAAAAAACGlsc3QAAAAIWHRyYQ==";

    /// <summary>
    /// The same tone as Windows Media Audio in an ASF container.
    /// <code>MediaTranscoder, MediaEncodingProfile.CreateWma(AudioEncodingQuality.Low)</code>
    /// </summary>
    public const string Wma =
        "MCaydY5mzxGm2QCqAGLObHEGAAAAAAAABgAAAAECodyrjEepzxGO5ADADCBTZWgAAAAAAAAAYL0F4HwjFEWW5DQUAjNo/SsYAAAA" +
        "AAAAhYRIjidV3QEBAAAAAAAAAADu9gEAAAAAcmcAAAAAAAC4CwAAAAAAAAIAAACIEQAAiBEAAEZ5AQDOdfh7jUbREY2CAGCXyaKy" +
        "IAAAAAAAAAABAAEARnkBAJEH3Le3qc8RjuYAwAwgU2V6AAAAAAAAAECeafhNW88RqP0AgF9cRCtQzcO/j2HPEYuyAKoAtOIgAAAA" +
        "AAAAAAAkAAAACAAAAAEAAAAAAGIBAgBErAAA4y4AAGsREAASABAAAwAAAAAAAAAAAAAA4ABCwAFrEWsRAQAAtQO/Xy6pzxGO4wDA" +
        "DCBTZeEAAAAAAAAAEdLTq7qpzxGO5gDADCBTZQYAswAAAKlGQ3zg7/xLsik5Pt5BXIUnAAAAAAAAAAEADGUAbgAtAHUAcwAAAMul" +
        "5hRyxjJDg5mpaVIGW1pYAAAAAAAAALgLAAAAAAAA4AwAAAAAAAAYdwEAuAsAAAAAAAAYdwEAuAsAAAAAAABrEQAAAgAAAAEAAAAA" +
        "7vYBAAAAAAAAAADqy/jFr1t3SIRnqoxE+kzKNAAAAAAAAAABAAAAAQAMAAIAAgAAAEkAcwBWAEIAUgAAAAAAdNQGGN/KCUWkupqr" +
        "y5aq6AAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAECk0NIH49IRl/AAoMleqFBwAAAAAAAAAAIADABJAHMAVgBCAFIA" +
        "AAACAAQAAAAAAC4ATQBlAGQAaQBhAEYAbwB1AG4AZABhAHQAaQBvAG4AVgBlAHIAcwBpAG8AbgAAAAAADAAyAC4AMQAxADIAAAA2" +
        "JrJ1jmbPEabZAKoAYs5suhEAAAAAAABgvQXgfCMURZbkNBQCM2j9AQAAAAAAAAABAYIAABBdAQAAAAAAAgABAAAAAAAIaxEAALgL" +
        "AAAIAAApH3f/6gDgACBAiN48AAKFSsAznGQfKDSW9n0lvZw2gENsNT01hzgqIgfVAfToBvLABaAYAGmDBgwYMRBXH7K0MKlYJdrb" +
        "MGVd2X2YMqGQfCCNjY2BNoB8DYKZLEPs310I6saVmqCxgVBhgHqQjngp/j1VaGDSsJjbqZjYVMZBsHvobAS0AmhcXov4QTK0UqAm" +
        "QhpAliWOZD9i+zZ/TeSuRHq0MOlYaBAM1VmJsuEAzVWYmyjIMAtCEWVZsELH1hUgtaFfJKEZ1GqCn+mGIjMNhGDWP1KVvhR299h9" +
        "g8oGVx/atDDkJ6LxI2Xr/ReJGymvjILAhEMIhCsLFR6g2gKIsmspxCw9loOapNDuMIgrpK5Fb0p6V6B+SYBnQwLYHGDC+mbQyLN7" +
        "90Uea829CLzEEUQ2Bxn/vKYYzY5J5gvrYXAC5tiJSq7FeEh8AEmgPA/YUmF3dAhVs6YJuB0VR7vp83gnOAh3QIVbOgE0gcap7vp8" +
        "1wTnAQZAoBDDmR0cwAbDNaqqHyGHMjo5gA2Ga1VUPjWXQSglV6EJ3D26oekpYq2gM1obMdhCuCOcOVQvPHp4TpBOikqUlPo4vT5q" +
        "UCRhuyu2twkOqKdT6CLttV1N3ml3gzjwM8mcWdzN+ZezWMWOffvTszabzXuLHPzm+85BSZ02YHX8S4cuwODQARhbBChgnJROyW2x" +
        "vMyG0+fKKai9BVlRYDVwIkJt9AYWd3J2CBRWrMf82wEUU29WcCQ/IvjHZ2NloDWbA0ijzNllD4nP4Y+mzkwOb8y0gtzFPZzR4+h6" +
        "CJwjgaEHzn+2tovUIqFNTE6geJUKnArwkpgAkzl4H7Ck0RTdWWhoXkvODvZTZ6SIPkRELm6stDQvJTOPe4dnviCcixCGQNAQ5HOO" +
        "b462Ga1VUPkORzjm+OthmtVVD6tOEb5mknKMWg8bIW0BVJDaAjw2EKky2YDBXm/zf5/TZOF3HQZA4r3LAPHfkmnVrO5NrWcea5nw" +
        "0K9fpEzMzPPjxzMc23m4eLAknlxUa/u4sepCO9Pm359+0nZxy7WKbi17ffrmHbX6zx8GLmmZypNbBV2ZeXeozL5lkOwULAL8XbII" +
        "sTCi2RbwgG0QQjbL9GF2D/gMg7LfzIfZ+U0w+yx4uDZ7KBpuWyROzhRz/DmLRkjj4dtGWFFYwwzzNxmASPw+lzsGWYTJpSnm/Ihn" +
        "l8lziPYI2qm0VqZfTxrGZXhI1ABJn7wP2FJhdxbyowrwnAOMCKGC9Q85Kn7L4scq4UcJwO4EUMF6h5yVM7KMgaAhxDnHN8dbDNaq" +
        "qHyHEOcc3x1sM1qqofBTZO1k7WVBFrCPRzZZWgJFcbQEzKZMdZi2BmBFj+Y97Be1a0NGHQpn1QNvYUNqVQ6wZht+NlOgnM7M/Oda" +
        "/hb2pnUzmZOzgT88eLN+nUefMzn30MxFxpNA6Th/rEjx11jF3eZLk/csTAG2tw2beF8/Mv2rQJHYb05/yCz7poZ8E9CE1GKOyarG" +
        "xVjlFF1aPavwH/yez5eo2l5kuimNKIC/1mRRs/kf6d2A/g34mSmQSRRt3EIxDJOfdnLa84BCXEL5MPhzzqYoSe6wwPG02x9ghqr8" +
        "IQqa93d5eV4SeQASZq8D9hSYXcdetRDfCSmwbeKKieJXpeJ5x160YacJ3YN+KREyJXpeJ4yBYCPHMjo5gA2Ga1VUPkeOZHRzABsM" +
        "1qqofBAZBJgIMkBDYSmwom0B6bjZc2ERI0YU+7supMgBkKMg0gANA3NHarWtahJIqbqS5FOEnNjrFl872eHMS5mPNPmalpv886/n" +
        "Atpk6Zu4t7HnAnYWb02ZhzMedbVv4F6ZAmtSKPmfycN+Z5utNt+POTqxvIk7An9/KgaK2Rcyh/foH3rUwI2Hk0sfQs9W+tkWTDJv" +
        "fX7/r3nyEws+CKkSNsczMoJWaT8Bv2hsWHRNwHYwnGahhdrWcatYF1p+A5Wi3QTeMwyl8TdHrMHYrHDCREIFrIvwIlE03vVS8sQR" +
        "MIJV4TQwASf28D9hT6IkN3odDILEg7MwTikg2YwkGYHQsC95gTnk62ZTOVpu9I0MgtkHzMZxYIMzGQQZgcVgX+YE55OszKE5QyAo" +
        "CMOgHMjqsM1qqofIw6AcyOqwzWqqh8LyBACIk43ichkvk2VY8CYuw2Itm8I2CQWISdEC07PNBFmhcSeq/Wmsgf8yAHy7j+GQeRQI" +
        "HdiYEQxg8gvPpjEdAMVlKCfMNZeEgt4Qw/1rfUHgGZAF/ynSLoU+j0i6GHB+tdCfB86AKjB9vAFpT6PSKBT6POgDDg/AoE+D5tQm" +
        "QfrQBMp9vSKBB8H0igT7edQJ8HzoA1bP60AasH60ATIP1oAmU+bOmYdHwL0+3zuZ38zpm/nFnDzizPzngzjzlCfibRLbhoQ3EUSq" +
        "wKrYhEC+yuIVGgrwiZgBU9JOleBaFPm8S/QbB+o+TGpOpuI2Hcu4hzQCJEylCyKNL9BiD2o+TGpOppEbDrLuIc0NEsywheKBkDwF" +
        "Y5wVhmtVVD5WOcFYZrVVQ+EpyqOoWg4rLQw4TELKPX1ELDlHrsIjYgGGoUVYXmwkCdRYQ8RkI82PMpgMi0VUDz1MEuEJCHNpFaej" +
        "mHNUn0IdqJ0YXkHkEpiDHV0ow1UrEVbyFgTS3rUHqtZSl9LWb82ysIrNU2yuEF1YMC1qCteBZkFTYFtYKtqbQqVRabAuFBWDAuFB" +
        "U+BZkFTYFmUq2ptrSrbBoWFRcGBcKCp8C6l2teBdSCteBZkFTYFmQVNpszCtsGhTqLPtc22aFmlZxZyglXAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzA==";

    /// <summary>
    /// A quarter second of H.264 video with an AAC track: two tracks, so two sets of chunk offsets a tag writer has to keep right.
    /// <code>MediaComposition { one image clip, one BackgroundAudioTrack }.RenderToFileAsync(MediaEncodingProfile.CreateMp4(VideoEncodingQuality.Qvga), 60 kbit/s)</code>
    /// </summary>
    public const string Mp4Video =
        "AAAAGGZ0eXBtcDQyAAAAAG1wNDFpc29tAAAAKHV1aWRcpwj7Mo5CBahhZQ7KCpWWAAAADDEwLjAuMjYyMDAuMAAAEIFtZGF0AAAA" +
        "AAAAABAAAAACCRAAAANqZbgEGf/8RLwKO8TJ/GLF1UmLbY+Pbd8/t6Echz52ZLw1ffnHKzGY4Vm3H2vpVN/GrDtQlwsO1XqVZZt0" +
        "oUsAsNlRkqVwbYr6A6ZIf5+D00+wwpOWeObNzpbnLyX/cHDd6bkcsWjraaj3jPNaGu6uwquXE3aEKSS+vF7jP+g/Q58P3xTXyZw4" +
        "ZUJq+P1v21kwwItZdKD5RElplTC0yheHWL7VNvCyZLmbNxBaVcIIUcjxDay1tlvEIkqNeKKq811d4Pd5s7xP/SA+YPBO/xXzFdp7" +
        "VUicd9FbSla6SeVpKdMCgxZF6Me4myX6VoGb60SBcL7qx/k7UM2hx5OpGqaUx7NmztbJoZb6kHs3H2SAXIMrGlafH130X3eE4Cde" +
        "EEX49IRf7QO+k3GoF9kDEBpWPUD4auHwodsozCBS+MAF80+PXtUYOOHSHL0Jee5ykB89yepJyiSJj2LBKlSSViWhIHuIrS5IgT/V" +
        "nf+LrSAGMpBS4zk/poafT7Qw8zkdmbtUvFixBVC8rJsCBboxQn0KSl7HHZ8c6OPV9U/VlrNzbJj+GQl6os/rD6rN/MKc16/hP1ej" +
        "j5HBSkjvEbckJlVQnkxta0O+1PMQF5BOeAy7KvbSGILfG9UsX74Q0H9Wk7pE8k67KTLrJLzr856jXyAfr8PR4YuuUILetv9Kc/Pf" +
        "BvcV06nJrJKvbxeWEiLGS73R8EBUosx9vOuSkIyCHgvwx5v3EmSfGpIF25sd99zBuCSvRPxuIAQU3kO5LsbaoOqa9pFsXhGkj+/2" +
        "JUCyWFfkQQwulFeihMxwKOPA2FUyxVQXHfEoQQO7L8otFx55lqzTa6o8TFewqQeEKJxFOPzEWQBmx+QnydHxVSLbEHPShy+QLWBn" +
        "Toa2tQ8haLJxJzs2s274EPyMsuuLueAT4RIh9+NRoIaQdVdY/Wx4Q1pkxcuQcAIzSl3bVAQ8g27+tVGBirdS5ZXFJIDoxCHrem/W" +
        "uvYNWsxhmjQALiL+3raEFIZMqXt8ZrM4oQZMqUQPRdK1WPvdu0s4wW4ppH4xegulfIcX0pJRS+uYJ69IkeNvz4Mu9kIiZ8p/p5mC" +
        "PvH4RQfz4UBhYreNMbnjrD/WvRDjwzGBIfGezBMjGZkG9U4c2Zj49IgKoFAJomxONuRV1Z89/bvtYDLPevaugAAAAAIJMAAAABFh" +
        "4CIr/wEkJ7WyeFhxPQS+uQAAAAIJMAAAAClh4EIj/wDyDiEfzV6gwRgjyiVNUPzGxLOmv/6zpcpFVRvNGUfmfqw3IAAAAAIJMAAA" +
        "AF1h4GJPA4VPOK3muT6LpD7UzjCxsc4cB0aNNepgNycuklzGNRVyi5Jsyd+CMwDeE86A8bZSxcAC9AiKAcQskRgwiVNFhhuKIke1" +
        "96Fzgq5FK1OPShxLucAROK9o9IAhelP1rhjRQIOiy93YSLCUSoqUUKV+wkQmybdJ3fHxDP0gDjXskiIJEIP4vzOYYaggVPW1bVPR" +
        "Zil5Ox2OKiSFyD9tsqSUZ5lu5tUaL5rJpIuvOga1mo1KcDbpUqkmIq/YVFGRew2tGNUUCJ0si7yqe6t6zGvFG0TDqt4aQd2BJpsc" +
        "zWvI3rrRU44hJ2yyz3Akm6p7dtLvaMFpRpAMHUGKem9AU4tOW+yu8hqk3oiIquTa8XmbTyvevhBbbAK++69Re55yGnypfq3nW5kW" +
        "5JjiMaEv64c7Ck5bi3LZTRU5TNLQ0mIFN7bJlSqqU7Fts5bVoZJXipLhpgWE7Qvnc8rSpF6pUTZliNNAWzTUXyLIAEUcKU87nofU" +
        "OiEaUgWQBMyCtJ//zHk0SVUgrQIpMkoAAyLXOWIu9gEswbH4EQlYNqVJpYe3q1y9esZ8d9Bnjnj293eC7uDvXPvn0DRZ0b9RAIVW" +
        "/VAdKuHzS5We1l03rqoTtkoXmw9+/UuL5SrmM8TXvXwp3H4Klg2dtcenrz2nRPORyPxspVbrtSvPN3Eq5V9QUVX01M/NpYC7m/nD" +
        "pGGyJ77yeSTOvTdZy+11XXliLxo92zXuIcK7x8KVmeulcUwxilx51XBM1dC5693Vr1K9PBBBbqlimgZ1yv1hLC7hknlq62tg9l2f" +
        "cxVQlR2SzS8bNFz7BOrKMriRqrOjVi7X1WDwbUfO3xrB3LKlch6ppg3sygS6HoRaVAAA9D6h1CEaU+2QBxBjQFlh+BUQm5dSxSAS" +
        "igWEk8dwRHGeWCXWw2fHTE1lKJNrn7mmkWYzxM5tmSqzt5IqlsdtBd1LSESvakt0EyxBGRaMDFeJdFjsNzSxB3pek33jupN1Gsbw" +
        "tx5tSUxPb01XvNKv1kEwuwwAHkvXC/+e2yvKh8t709u2qkNxEAnNnZA5LUCTxZjDNdOiDVPiRtpMKqkDkiYzcqjlrvpFF3DLNWuP" +
        "gt3fvrkkvL32LnJYPLusZerXPtuJ5y1FnnOWf3s0FbVfN3PspPfwr2osDniCUIc6xNUCT0ScYhZMbaZOzDGyTv1+B3TS30nPFJKK" +
        "XIMgYMGE1wNOPFPVKX155gk/7fBWq12d8OVU5z7wi6RQAAPQ+ochGlPFkAURaQhwiU3xKUuEpAVBQBnfM75Yj0r2AS+Ipie2DIQT" +
        "GLLM1JbQNSimlRKkFEevFomn0uOekNbZMeiXVxH6c+hWZa6iS2Auj8c6zjQMPkYAuukjgrqFrWVEVuzLf0dmmunJJhq77BVTGPsT" +
        "gCNMle/OuLUkkvutr7656EzKx0ziRCJslqU5aLLaMU8t2WzRM2WqYJFugy8Zce3v6hO4+z1clBZ7Sk39tKRrBudPy0+7WmON/bj3" +
        "4ZTVEGRUjXfqkP8b91dE+Ul84YP679kU0d1u2nb66zJ6gvutClYkoNIvid+59zTz023GVfok3zrm3X39nYOdVsCI7bAGPxcverlX" +
        "LPInP3/zBx4TBSrHYyzQsX+DAAAeh9Q4IRpTnZAHEGkBFZxVSWKSCoKvCUICmis/wiPq3mVZfjSl/ru9ojZImBW1ZgXlgTQU+U6i" +
        "i3gvRLXOOUejZBCzdRY/jXXWzAC5TMkm0zMjZlXkK3QT8Mli6an1W/qipQt5KOVJdILlYdtn6plY96aBHglC8azz7IyzzOjyfjuq" +
        "1x+LcbtUnmwUFO455Zp/VuIa7teK10CJBTUA1BmgyNg9yJItSBpskvGRaqqY0hvf6kvGwd+7zbCxXyVxZ0piO+eqwN1q86mF7Jx2" +
        "OzsPryk4ZDTqiyvTSx/U8KvtZdduLG7MNQJ5EoDUR0gp7Ztkx0Zn1+XRUc6zt3+E+FpO2RjJBM0WHdiS2buyTveifUUmdFa38rDI" +
        "jVwAAPQ+ocIhGlO9kAcSaAdExFWQWCCoFYBU1KSlkSHcPUxP5aFwLeRvfRhKz3mS4r2WdoVJdMO8UqgbKfjLnPioaQqosGAzEpHY" +
        "jwPyRIW2GqJx54Jd63nRbquIvsQXqxld6FvZvGDTOJtzPHPYw26cJT0m/VT7w6g8u2d+TlTP6cmJb53fN/f3/x3bLEDvn3S1k1yk" +
        "FejDM25a8OFDz6Qum14zYssm8440aspp0NqRwPzXYkW/pnTXo19tFEtwxZfLJd7rqqN8snPhc+ckTlJQ99UFMMtNeFNFfLX0pu19" +
        "pXPrmm6dVPpmitymXYVMuFmjpNnMOFlud3q3c+6/MpNmX5fsLA/2mWm/sla/v07c9MvlCv2K0WEAhw2OEW2z2yOo2rUAAB6H1Dwh" +
        "GlP1kAURaRT2aajJS6q4lXkgCoAaEIrqsQwXd7P59RUI+ckLiVBYvlCnkhky4idpTSZScJEi2dAnTROukWa2pZeG44n44GBwNWMa" +
        "fXGpyWjv1bGRxkCbv4uqudFEKD3/CmimT2KKO0XSYnW0ndBgcuF9JXeNqowbb+echSS415oi0KCEyzR3MOcVoWGjluibNk1XXB0n" +
        "7a0vfu0axuwiOvTDUTon71+bBwplq8Hu8NFXVLJA39MV9nb4YS+namhpNytLmtwznGxfUCJJ9g76H2YJP0+cFxCfKIKeMwr1ezZ3" +
        "kovJW/QpFS7f6c6CqwLhVs5vx3vqWOubn21eu7hLQmqy+2w9V8tQcuuzTvXK3KqseXbzAzovAAA9D6hzIRpTxZAHEGTBWIDokM0y" +
        "JVqtVXFSgoGpPNK64cQyXzkJ9riEpSmMZoF04z6qeGWwklaIJ1OgD7l9RcS3mlyZOFkgjG422iCC3E0JbQE7ecw6B+nHkoVT+xxI" +
        "8gdyaqp4/IoR0L7J/JaNvOa91Ki7NwsNnKcs6WI4ukXRZR1XUbZ4SzVV1bs5eRy988/CTvOjfhfbrvIs5L4Z+wTrF3OoBTKi9orb" +
        "PApa76rpc/nlqeG+el40+Rcp2UKDEkmaS2lAtmLHyySm0gMwF1wt8iEYK8suxy6BBbBaGAbKIoyDOFlJZabyULx7GEwk2A6JR4aA" +
        "byIxwCvx0bMKlG2oUfDn3Lfqlr7LJbZzbizYHqH7rwEMzl7SrCiDSSuSMgjNAAAPQ+odIRpTxZAFCmfAWLAWGEasqCzJWoBGXWay" +
        "8BSD9iuuIEsD87SPOopCCqcjBIU23FhoNWKOWdVkhTeqMEwSV9jRoO0RU2wrMXm3B66Iky++p8+Mu31hevfPo2bp+5v58i7vmVm2" +
        "vNPr9Li4MfbYVkjbNuNgVdWGU2jOTsa9t0pXS8wm3zcXfjSiYWyJbyOWuMdenaMnEJOB75Lsd3vspabTjZ0WfUsx1HT5czszsm7X" +
        "W+wdNB/x34m9hXQewzZCSaXL5N7beKnXtafnTz1i82NxViLIt9k05vr0/1wnH5DjUkdmOQuc9oynjOGd/KxRF3WQ4MaDoAEbE0hG" +
        "etcnVyi0UhUpVvJ7u9GUbsOq7PFrurDLdVTZxvevH4ERScRluqlWoAAD0PqHIRpT3ZKTCWkgXgPjy3oM0VFSRCpkiqtjWQIEaUnZ" +
        "mDgtq0JJKh0WpeD2IuA07BYPerJ2X8uzYw4toSzfnQt3GvEaMgc6xRUKZKUJJuBnM41TPUEsGOhJnzBTBIZNrACQaUw9h0HHkllC" +
        "mUFz6h154K7HQK3Wj6a++yWuM77fXK1yq/xSVJttUXXylEzW5YvFGm/Yi2xLTvnKXCuCu++BXz5sW2oe/5SYHlaM/NcqFxuWlepO" +
        "gZGAX58+rjnflHtePL0fjetyzw8sMBWUxRKG+WzvuxUckELbOqVJq242ki50XLpHKTsahZKDc7eMtyYTWugQNJyXynUkS92JhQDE" +
        "YA0L06uzG5K8kSoGiTMRmpnCk5o6SMdhkU1j86uO56H1NZAgRpSdIRpUBbqWwyYIQPbXwHHcQTNbsoAGNZSIweAgAoDEXxED8evJ" +
        "Fkkp8YmERGHMIzY0soJAHyf9xvQkU/c5FKv3BO6WgRd/eLcN4jorVWG3jlKqrB0DP0bdu3h51VecvmKV4lhWqjlLCOgcbRY6Bfa9" +
        "d5Gq5KrSKyzK51JilbWCsSeNosdfvr1DV2Fkl0jKkpcjKsy+yqLEnxLCxJ/19Qk2K8YoE4KHXGJDxh6ZiFkrGmZxYsFaHEK5KZkG" +
        "nnybsufLnyNZGs3NmVBzc827mgf3FnyZx75Fs0Zj8/NmObLAWeZ0mvjOB8HzBuFPNBzNoz5XSzhoe40DQ3C2eDRnmM+ke75h7n8Q" +
        "HofU1lIjB4CACgMRfeIAAATWbW9vdgAAAGxtdmhkAAAAAObp7ffm6e33AACsRAAALAAAAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAA" +
        "AAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAhx0cmFrAAAAXHRraGQAAAAB" +
        "5unt9+bp7fcAAAABAAAAAAAAKxEAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAUAA" +
        "AADwAAAAAAG4bWRpYQAAACBtZGhkAAAAAObp7ffm6e33AAA6mAAADqZVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAA" +
        "AABWaWRlb0hhbmRsZXIAAAABY21pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwg" +
        "AAAAAQAAASNzdGJsAAAAk3N0c2QAAAAAAAAAAQAAAINhdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAUAA8ABIAAAASAAAAAAA" +
        "AAABCkFWQyBDb2RpbmcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGP//AAAALWF2Y0MBTUAM/+EAFmdNQAyVoFB+wEQAAA+gAAHUwDxw" +
        "ioABAARo7jyAAAAAIHN0dHMAAAAAAAAAAgAAAAMAAAPoAAAAAQAAAu4AAAAcc3RzYwAAAAAAAAABAAAAAQAAAAQAAAABAAAAJHN0" +
        "c3oAAAAAAAAAAAAAAAQAAAN0AAAAGwAAADMAAABnAAAAFHN0Y28AAAAAAAAAAQAAAFAAAAAUc3RzcwAAAAAAAAABAAAAAQAAAgF0" +
        "cmFrAAAAXHRraGQAAAAB5unt9+bp7fcAAAACAAAAAAAALAAAAAAAAAAAAAAAAAABAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAA" +
        "AAAAAAAAAABAAAAAAAAAAAAAAAAAAAGdbWRpYQAAACBtZGhkAAAAAObp7ffm6e33AACsRAAALABVxAAAAAAALWhkbHIAAAAAAAAA" +
        "AHNvdW4AAAAAAAAAAAAAAABTb3VuZEhhbmRsZXIAAAABSG1pbmYAAAAQc21oZAAAAAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAA" +
        "AAABAAAADHVybCAAAAABAAABDHN0YmwAAABkc3RzZAAAAAAAAAABAAAAVG1wNGEAAAAAAAAAAQAAAAAAAAAAAAIAEAAAAACsRAAA" +
        "AAAAMGVzZHMAAAAAA4CAgB8AAAAEgICAFEAVABgAAAF3AAABdwAFgICAAhIQBgECAAAAGHN0dHMAAAAAAAAAAQAAAAsAAAQAAAAA" +
        "GGN0dHMAAAAAAAAAAQAAAAsAAAAAAAAAHHN0c2MAAAAAAAAAAQAAAAEAAAALAAAAAQAAAEBzdHN6AAAAAAAAAAAAAAALAAABGQAA" +
        "ARcAAAEbAAABHgAAARwAAAEjAAABHgAAASMAAAEmAAABJgAAARMAAAAUc3RjbwAAAAAAAAABAAAEeQAAAEV1ZHRhAAAANW1ldGEA" +
        "AAAAAAAAIWhkbHIAAAAAAAAAAG1kaXIAAAAAAAAAAAAAAAAAAAAACGlsc3QAAAAIWHRyYQ==";

    public static byte[] Bytes(string base64) => Convert.FromBase64String(base64);
}
